---
# Commands to start on workspace startup
image: gitpod/workspace-python-3.12
tasks:
  - init: pip install -r requirements.txt
    command: make livehtml
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview
vscode:
  extensions:
    - chrisjsewell.myst-tml-syntax
    - MS-CEINTL.vscode-language-pack-fr
    - streetsidesoftware.code-spell-checker-french
    - streetsidesoftware.code-spell-checker-french-reforme
